export enum IntegrationHistoryEntity {
  client = 'CUSTOMER',
  invoice = 'INVOICE',
  product = 'PRODUCT',
  payment = 'PAYMENT_METHOD',
  category = 'PRODUCT_CATEGORY',
  brand = 'PRODUCT_BRAND',
  order = 'ORDER',
  store = 'STORE',
  itemsPriceList = 'ITEMS_PRICE_LIST',
  commercialTableItens = 'COMMERCIAL_TABLE_ITENS',
  promotionalTableItens = 'PROMOTIONAL_TABLE_ITENS',
  user = 'USER',
  seller = 'SELLER',
  accessProfile = 'ACCESS_PROFILE',
}
